[features]
seeds = true
skip-lint = false

[programs.devnet]
autosup_partnership_nft = "5YNmS1R9nNSCDZB5P7F3YTvGRR1Px2JnyM7FQNHpdYSw"

[programs.localnet]
autosup_partnership_nft = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[hooks]
